# Generated by Django 4.2 on 2025-02-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_direction_customuser_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='direction',
        ),
    ]
